### ISSUE TITLE
menu-background.jpg resolution is incredibly low

### ISSUE THREAD

**Issue by Corne2Plum3** [greenmg2003/osu-Mg-skin#15]
The resolution of the image `menu-background.jpg`, used in the home screen is way too low, even for small screen. You should find a better resolution of the image, at least 720 px height.

![image](https://user-images.githubusercontent.com/57914482/154844689-af9d765c-cb61-4710-8b91-febe3b3a51dd.png)

**Comment by greenmg2003** [comment]
Ah god, my bad, didn't have time to recheck this, sorry '^' ""
Thanks for reminding me!

**Comment by greenmg2003** [comment]
Maybe I will use this? It's scaled at 2160 x 1214
![Mg's anniversary banner](https://user-images.githubusercontent.com/65149680/154845038-0ac90d87-6f44-4a74-9b63-f722eea3683a.png)

**Comment by Corne2Plum3** [comment]
> Maybe I will use this? It's scaled at 2160 x 1214 ![Mg's anniversary banner](https://user-images.githubusercontent.com/65149680/154845038-0ac90d87-6f44-4a74-9b63-f722eea3683a.png)

Yes it's way better. You can use any picture you want. Note that the minimum to have something correct is 1920x1080 and the best would be 2732x1536.

**Comment by greenmg2003** [comment]
> Yes it's way better. You can use any picture you want. Note that the minimum to have something correct is 1920x1080 and the best would be 2732x1536.

Thanks! I'll update it in 3.1.2, 4.1.0 and 4.2.0 as well! Just let me know if you need me to fix something else ^^"

**Comment by greenmg2003** [comment]
Done fixing, I'll close this ^^"
Also, you can check out this element in branch version-3.1.x for update! I'll upload files from 4.1.0 (WIP) and 4.2.0 (WIP) soon, then you can check out these branches :>
