### ISSUE TITLE
Accuracy counter overlaps the song progress bar numbers

### ISSUE THREAD

**Issue by Corne2Plum3** [greenmg2003/osu-Mg-skin#16]
In the following screenshot, the "%" of the accuracy counter overlaps the "100" from the progress bar. The "75" can be overlapped with other accuracy values. I suggest increasing the spacing between the image border and the digit itself, so the accuracy will no overlap the song progress bar.

![screenshot741](https://user-images.githubusercontent.com/57914482/154846509-6d004f8d-c5ea-479e-b2a9-d5a156577860.jpg)

**Comment by greenmg2003** [comment]
Agree, but there is no spacing mechanism, so instead, I'll decrease the size of "%" to make the spacing (maybe?).
Thanks for suggesting!

**Comment by Corne2Plum3** [comment]
I mean, you can just keep the digit "as is", but just increase the spacing at the top and at the bottom of the image, as shown below. So the song progress bar and the accuracy will be more spaced

![image](https://user-images.githubusercontent.com/57914482/154847246-1c6dc042-c685-48a2-ad60-129d70085330.png)

**Comment by greenmg2003** [comment]
> I mean, you can just keep the digit "as is", but just increase the spacing at the top and at the bottom of the image, as shown below. So the song progress bar and the accuracy will be more spaced
> 
> ![image](https://user-images.githubusercontent.com/57914482/154847246-1c6dc042-c685-48a2-ad60-129d70085330.png)

Many thanks from you! I'll try my best to fix it!

**Comment by greenmg2003** [comment]
It's fixed now! Will upload the files soon ^^
