### ISSUE TITLE
Suggestion: add border between the bottom buttons on mode selection

### ISSUE THREAD

**Issue by Corne2Plum3** [greenmg2003/osu-Mg-skin#18]
You should add a line, a separator (and eventually some spaces) between the Mode/Mods/Random/Options buttons from the song selection, it's hard to differentiate the buttons. It would also look like better if you apply these modifications.

![image](https://user-images.githubusercontent.com/57914482/154847524-3272aa16-edb0-4458-88e5-3d2f0ce273b6.png)

Also the icons size at the bottom right of each is button is not the same for every button (random bigger than the 2 other ones). You should use the same size.

**Comment by greenmg2003** [comment]
I'm not sure about the size. The last time I checked, those images' size was maybe 80x90. This time I checked, they are all 77x90. Weird...
But okay, I'll use random to make line separation. Thanks for the suggestion!

**Comment by greenmg2003** [comment]
> You should add a line, a separator (and eventually some spaces) between the Mode/Mods/Random/Options buttons from the song selection, it's hard to differentiate the buttons. It would also look like better if you apply these modifications.
> 
> ![image](https://user-images.githubusercontent.com/57914482/154847524-3272aa16-edb0-4458-88e5-3d2f0ce273b6.png)

Would this be better?
![image](https://user-images.githubusercontent.com/65149680/155111974-9770bdc0-61e9-452c-8045-6dfaada172b8.png)

**Comment by greenmg2003** [comment]
Feel free to comment this or open this again :>
