### ISSUE TITLE
skin.ini: 'Version: latest' should never be used in a public skin.

### ISSUE THREAD

**Issue by Corne2Plum3** [greenmg2003/osu-Mg-skin#20]
You shouldn't use `Version: latest` in the skin.ini, because an update of the osu! stable client may broke your skin, because it will use the new features, but your skin isn't made of that.

I suggest using `Version: 2.5` instead, because it's well documented and it does not change anything of the skin.

**Comment by greenmg2003** [comment]
Alright, I'm fixing this. Maybe you can check branch 3.1.x to see if this one is fixed or not.
Thanks for telling me!

**Comment by greenmg2003** [comment]
Done, you can download the new skin.ini file from the 3.1.x branch to update it ^^

**Comment by greenmg2003** [comment]
Does it function better now?

**Comment by greenmg2003** [comment]
So far, it's better, like what you said, so I'll close this first ^^"
Feel free to open this issue again if you need. I'll always appreciate your contribution :>

**Comment by greenmg2003** [comment]
So far, it's better, like what you said, so I'll close this first ^^"
Feel free
