### ISSUE TITLE
Some issues about the Ranking Screen selection

### ISSUE THREAD

**Issue by Corne2Plum3** [greenmg2003/osu-Mg-skin#21]
![screenshot743](https://user-images.githubusercontent.com/57914482/154848420-97107d57-80ba-4f08-a5b0-57afaee83544.jpg)

1. I think the ranking-panel is a bit too small because you can have informations that overflow (i.e. goes out of their limits, like mania "300", "200" and "50", or values with more than 4 digits). I suggest to increase the width of the panel.
2. Why the bottom right corner of the yellow part isn't rounded? Did you forget it?

**Comment by Corne2Plum3** [comment]
I forgot to say, but every issue I posted were from 4.0.1 version

**Comment by greenmg2003** [comment]
> I think the ranking-panel is a bit too small because you can have informations that overflow (i.e. it goes out of their limits, like mania "300", "200" and "50", or values with more than 4 digits). I suggest increasing the width of the panel.
Definitely true, I'll resize it in 3.1.1 to try if it's better or not, then I'll fix it in 4.1.0 (WIP, from 4.0.1) and 4.2.0 (WIP, from 4.0.3)
> Why the bottom right corner of the yellow part isn't rounded? Did you forget it?
Goddang it, I forgor 💀 . Sorry for my bad '^' "
I'll fix it in 4.2.0 soon
Anyways, thanks for helping me!

**Comment by greenmg2003** [comment]
![image](https://user-images.githubusercontent.com/65149680/154915253-a69cc562-dedb-494c-befa-4bb3af20a774.png)
This should be fixed like this. And it's okay unless there are at least 5 digits in the second column and 3 digits in the first column.

**Comment by greenmg2003** [comment]
Feel free to open again if you want ^^"
